### PR TITLE
cleaning up the code

### PR DESCRIPTION
**Pull request by SenadAlagic**
Dividing the whole code into 3 different corresponding files.

### CODE REVIEW

**Comment by SenadAlagic** [comment]
Also fixed the issue #61

**Comment by waldyrious** [comment]
@SenadAlagic I hope you don't mind, but I'd prefer not reformatting the CSS code as much, at least not alongside this move, as that complicates the diff, and I'm not yet convinced it's desirable. We can discuss using a consistent format (e.g. one declaration per line) in a separate issue. Also, the bugfix for #61 should be a separate PR. As I said in #62, I'm inclined to use that PR to implement the fix, but adding you as a co-author.

I have already made these adjustments locally, but I cannot update this PR because you sent it from the main branch in your fork. Could you temporarily grant me write access to your fork, so that I could push the changes to this PR?

**Comment by SenadAlagic** [comment]
I apologise now because you waited for my response. We really can't seem to communicate in a timely manner 😅. I will grant you access to my fork, definitely. I would love to continue work on this project because, as I said it many times, I use it almost daily and I would love to feel I contributed. I took some time off but I will return to fixing bugs and resolving issues. Hopefully we can fix up our communication and improve this together!

**Comment by waldyrious** [comment]
GitHub got a little confused when I updated your `gh-pages` branch, and closed this PR, with no option to reopen it.

In any case, the fact that this PR was sent from the main branch in your repository was precisely what stalled my previous attempt at addressing this PR (I had to first get write access to your fork in order to be able to update its main branch, whereas PR-specific branches can typically be updated by the original repository's maintainers).

Next time, please create dedicated branches before sending PRs, as that will make the process easier to manage for everyone involved :)

**Comment by waldyrious** [comment]
For future reference, this PR originally included the following three commits:
- 36b96aa  2022-05-27  Alagić Senad  cleaning up the code
- 397a476  2022-05-27  Senad Alagic  cleaning up the code
- 8e4b35c  2022-06-19  Senad Alagic  fixed the download file issue

**Comment by SenadAlagic** [comment]
I apologize for any inconvenience. I am still relatively new to lots of things regarding Git and Github itself. If I understood you correctly, I didn't create a specific branch for the PR so it caused you issues. I'm not sure why I did that but I will definitely pay attention in the future. Many thanks!

**Comment by waldyrious** [comment]
One reason that I can think of for creating PRs based on the main branch of the fork is that if you have GitHub Pages set up on your fork, then it will allow live testing of the PR changes (i.e. the changes would be live at https://SenadAlagic.github.io/browserpad). However, changing the source branch for GitHub Pages publishing is fairly easy and quick in the fork repo's settings, so in practice there's pretty much no benefit to creating PRs from the main branch.

**Comment by SenadAlagic** [comment]
Oh, well, since I use VSC with the Live Server plugin I already do have live testing enabled. I would definitely use GitHub Pages otherwise. Also, I don't recall setting that up but it seems it's already somehow set up. I see your point nonetheless and will create separate branches for each PR.

**Comment by waldyrious** [comment]
> Also, I'm not sure how to proceed if I am able to solve multiple issues before you merge the PR's from any of them. Do I have to wait before you merge the first PR before coding on top of that or do I create another branch off the main one regardless of the code written in the branch to fix the first issue (I really hope you understood what I meant).

I think I understand what you mean, yeah. There should be no problems with creating multiple branches simultaneously out of the `main` branch. Once one of the PRs is merged, the other ones simply need to be rebased, as I did in #62 for example. I'm happy to take care of that if necessary/convenient.

**Comment by SenadAlagic** [comment]
I'll wait untill that happens, I haven't had many chances to "rebase" and try it out. I should probably look into that a bit. Thanks!

**Pull request closed without merging**
