### PR TITLE
Dropping the CSS styling when pasting content

### PR DESCRIPTION
**Pull request by SenadAlagic**
Fixing the issue #42

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for contributing again, @SenadAlagic! I am wondering though if this is still needed, as I can't really reproduce #42 anymore (I tried using the [archived version](https://web.archive.org/web/20170919100133/https://www.keybits.net/post/import-keybase-private-key/) of the page linked in the issue, since the original has [moved](https://old.keybits.net/posts/import-keybase-private-key/) and changed formatting in the meantime).

Are you able to reproduce the issue?

**Comment by SenadAlagic** [comment]
Oh no I couldn't. I tried with the site you sourced but was unable to. Still, even though we can't reproduce it we should still fix it I guess. My JS is sort of rudimentary so I can only complete the "simplish" tasks, that's another reason I chose to help with this issue. Glad to be of help!

**Comment by waldyrious** [comment]
Hmm, but if the issue isn't there anymore, what's there to fix? We shouldn't just add code to the project that won't really _do_ anything... that just makes the project more complex unnecessarily, and will make the barrier of entry more challenging for other contributors.

I definitely appreciate your contributions, but unless we can reproduce the issue, my inclination would be to close this PR without merging it. Let me know what you think!

**Comment by SenadAlagic** [comment]
Hm, on one hand it definitely makes sense. Then again it's very possible that a ranadom user _somehow_ reproduces it, Ultimately it's definitely your decision. Happy to help!

**Comment by waldyrious** [comment]
Considering that the code will remain in this PR indefinitely, I think it's best to close the issue as unreproducible, and close the PR accordingly; if anyone is able to reproduce the issue, then we already will have the solution ready, and can just reopen the PR and merge it then! :grinning:

**Pull request closed without merging**
