### PR TITLE
added an svg "i" icon instead of the github one

### PR DESCRIPTION
**Pull request by SenadAlagic**
Regarding the issue #19, I tried to implement the Unicode "i" icon (U+2139) but it looked nothing like the images of it, the letter was loaded and backround was white, so I decided to give the SVG icon a go - it worked out better it seems! Of course, if you still want to try the Unicode way we can give it a shot, but I don't think it's right. Hope this fixes the issue!

### CODE REVIEW

**Comment by waldyrious** [comment]
Hello! Thanks for another contribution. First of all, besides ℹ ([U+2139](https://www.fileformat.info/info/unicode/char/2139/browsertest.htm)), there's also ⓘ ([U+2139](https://www.fileformat.info/info/unicode/char/2139/browsertest.htm)), which could be made to look pretty decent with a bit of CSS, e.g.:

```css
#about-icon {
	text-decoration: none;
	color: black;
	font-weight: bold;
}
```

Here's what it looks like on my machine:

screenshot

You could try it locally to see how it looks for you in comparison with the SVG.

That said, I really like the concise and readable SVG that you created[^i] and would be totally onboard if you still want to keep it instead of the icon. Let me know what you prefer.

[^i]: In fact, even if we decide not to use the icon, I think it should be uploaded to [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:SVG_plain_black_circle_info_icons) so it's available to others as a demo of a simple and functional info icon.

**Comment by SenadAlagic** [comment]
I will try it right away! Also, I'm not sure if those two icons have the same code or did you make a mistake when pasting the code. Did you mean ⓘ (U+24D8)?

**Comment by SenadAlagic** [comment]
I am unable to somehow style ⓘ (U+24D8) in any way. Any styling I try makes it invisible. The one on your machine looks really good to, maybe even better because it fits more with the theme (if it makes sense?). If you want you cant definitely push that version of code and we can scrap the SVG approach altogether.

**Comment by waldyrious** [comment]
> I'm not sure if those two icons have the same code or did you make a mistake when pasting the code. Did you mean ⓘ (U+24D8)?

Haha of course! Apologies for the confusion, I've edited my comment above.

> Also, I did not create the SVG I found it online, hope that is okay?

I think so. It's simple enough that it shouldn't really be copyrightable (it's just a circle and a letter "i")

> I am unable to somehow style ⓘ (U+24D8) in any way. Any styling I try makes it invisible. The one on your machine looks really good to, maybe even better because it fits more with the theme (if it makes sense?). If you want you cant definitely push that version of code and we can scrap the SVG approach altogether.

I'm not sure what the issue might be in your machine. I'll add the changes I suggested above as a separate commit on top of your branch (rather that rewriting your existing commit), so that if we want it will be easy to recover the original SVG approach, at least until the PR is merged.

**Comment by SenadAlagic** [comment]
I like that idea. That means you won't be merging the PR soon or did I misunderstand you?

**Comment by waldyrious** [comment]
Ok, I've replaced the SVG with the Unicode character in commit [1193891](https://github.com/browserpad/browserpad/pull/65/commits/119389198b559d58983329f7c9180ac99351072a). Funny thing, rereading #19 I realized that there are actually three similar characters, not just the two I listed above. The one I had initially identified in the issue was 🛈 ([U+1F6C8](https://www.fileformat.info/info/unicode/char/1F6C8/browsertest.htm)). I tried it just to be sure, but the current one (ⓘ, [U+24D8](https://www.fileformat.info/info/unicode/char/24D8/browsertest.htm)) looks better.

> Also, I did not create the SVG I found it online, hope that is okay?

Re-reading issue #19 I also noticed that there was an SVG code was there all along! 😅 The one you used in the PR is remarkably similar — did you adapt the code from there?

> That means you won't be merging the PR soon or did I misunderstand you?

Well, the PR would not be merged until the functionality to implement the opening and closing of the About dialog was actually implemented (which was the second part of #19). I was going to leave some comments in this PR with ideas of how to do that, but it turns out it was relatively easy (using the [dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)), so I went ahead and implemented it in commit [ca0b82c](https://github.com/browserpad/browserpad/pull/65/commits/ca0b82c21ca7500cee8f4940c4e66c516bb09f03). So this should now be ready to merge. I would just ask you to test these changes locally and let me know what you think.

**Comment by SenadAlagic** [comment]
> Re-reading issue https://github.com/browserpad/browserpad/issues/19 I also noticed that there was an SVG code was there all along! 😅 The one you used in the PR is remarkably similar — did you adapt the code from there?

Yes, yes I changed up the code, really, what I did was nothing much😅 .
>So this should now be ready to merge. I would just ask you to test these changes locally and let me know what you think.

Will test it right ahead. I will let you know how it works!

**Comment by SenadAlagic** [comment]
Works perfectly! As far as I'm concerned this can be pushed. I am happy with the work we did 😊 !
Onto the next issue!

**Comment by waldyrious** [comment]
Awesome, I like the result as well. So, as a matter of principle I would squash the commits to remove the intermediate stages, but IMO they are individually interesting (and make the diffs more readable), so I will merge the PR this time with the separate commits. Thanks again for the contribution!

**Comment by waldyrious** [comment]
I've rewrote the branch regardless to fix some whitespace issues in the first commit, since it's going to be preserved for prosperity :)

**Pull request merged**
